version: '3'
services:
  legacy-groups-processor:
    image: legacy-groups-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    volumes:
      - "../:/app"
    network_mode: "host"
    command: run start:docker
